"""replace soft delete with hard delete for vectors

Revision ID: 25235ae1c497
Revises: e7898746fdcf
Create Date: 2026-04-10 10:37:40.600621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25235ae1c497'
down_revision: Union[str, Sequence[str], None] = 'e7898746fdcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vectors_deleted'), table_name='vectors')
    op.drop_column('vectors', 'deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vectors', sa.Column('deleted', sa.BOOLEAN(), nullable=False))
    op.create_index(op.f('ix_vectors_deleted'), 'vectors', ['deleted'], unique=False)
    # ### end Alembic commands ###
