"""initial migration

Revision ID: 3f0935190fc4
Revises: 
Create Date: 2025-11-30 16:44:42.641289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f0935190fc4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('metric', sa.Enum('L2', 'COSINE', name='metrictype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_name'), 'collections', ['name'], unique=True)
    op.create_table('index_metadata',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'key')
    )
    op.create_table('vectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('vector_blob', sa.BLOB(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vectors_collection_id'), 'vectors', ['collection_id'], unique=False)
    op.create_index(op.f('ix_vectors_deleted'), 'vectors', ['deleted'], unique=False)
    op.create_table('graph',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('neighbor_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['neighbor_id'], ['vectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['vectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', 'neighbor_id')
    )
    op.create_index(op.f('ix_graph_collection_id'), 'graph', ['collection_id'], unique=False)
    op.create_table('vector_metadata',
    sa.Column('vector_id', sa.Integer(), nullable=False),
    sa.Column('source_document', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['vector_id'], ['vectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vector_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vector_metadata')
    op.drop_index(op.f('ix_graph_collection_id'), table_name='graph')
    op.drop_table('graph')
    op.drop_index(op.f('ix_vectors_deleted'), table_name='vectors')
    op.drop_index(op.f('ix_vectors_collection_id'), table_name='vectors')
    op.drop_table('vectors')
    op.drop_table('index_metadata')
    op.drop_index(op.f('ix_collections_name'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
