"""fixed id constraints for vector

Revision ID: 756d5ce8b995
Revises: c899d0e89a68
Create Date: 2025-12-09 14:52:47.778996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '756d5ce8b995'
down_revision: Union[str, Sequence[str], None] = 'c899d0e89a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vectors_external_id'), table_name='vectors')
    op.create_index(op.f('ix_vectors_external_id'), 'vectors', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vectors_external_id'), table_name='vectors')
    op.create_index(op.f('ix_vectors_external_id'), 'vectors', ['external_id'], unique=1)
    # ### end Alembic commands ###
