"""added relationship between IndexMetadata and Collection

Revision ID: 80ccb33575ab
Revises: fea48c4c5797
Create Date: 2025-11-29 10:17:50.203766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ccb33575ab'
down_revision: Union[str, Sequence[str], None] = 'fea48c4c5797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
