"""replaced graph table with blob

Revision ID: cede88021620
Revises: 25235ae1c497
Create Date: 2026-04-29 17:04:18.573437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cede88021620'
down_revision: Union[str, Sequence[str], None] = '25235ae1c497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_snapshots',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('entry_point_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.BLOB(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id')
    )
    op.drop_index(op.f('ix_graph_collection_id'), table_name='graph')
    op.drop_table('graph')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph',
    sa.Column('source_id', sa.INTEGER(), nullable=False),
    sa.Column('neighbor_id', sa.INTEGER(), nullable=False),
    sa.Column('collection_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['neighbor_id'], ['vectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['vectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', 'neighbor_id')
    )
    op.create_index(op.f('ix_graph_collection_id'), 'graph', ['collection_id'], unique=False)
    op.drop_table('index_snapshots')
    # ### end Alembic commands ###
