"""Create initial database schema

Revision ID: e0b2d1c78bcf
Revises: 
Create Date: 2025-10-02 19:28:44.661996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0b2d1c78bcf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_metadata',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('vectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vector', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('neighbor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['neighbor_id'], ['vectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['vectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', 'neighbor_id')
    )
    op.create_table('vector_metadata',
    sa.Column('vector_id', sa.Integer(), nullable=False),
    sa.Column('source_document', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['vector_id'], ['vectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vector_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vector_metadata')
    op.drop_table('graph')
    op.drop_table('vectors')
    op.drop_table('index_metadata')
    # ### end Alembic commands ###
