"""replaced vector_metadata table with a json field

Revision ID: e7898746fdcf
Revises: 756d5ce8b995
Create Date: 2026-01-02 10:55:59.389818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7898746fdcf'
down_revision: Union[str, Sequence[str], None] = '756d5ce8b995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vector_metadata')
    op.add_column('vectors', sa.Column('vector_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vectors', 'vector_metadata')
    op.create_table('vector_metadata',
    sa.Column('vector_id', sa.INTEGER(), nullable=False),
    sa.Column('source', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['vector_id'], ['vectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vector_id')
    )
    # ### end Alembic commands ###
